# Generated by Django 4.1.1 on 2023-01-14 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('title', models.CharField(default='title', max_length=50)),
                ('text', models.TextField(default='0000-00-00')),
                ('date', models.DateField(default='2022-01-01')),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(default='*name folder', max_length=50)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('order', models.IntegerField(default=1)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataControl.document')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dataControl.tag'),
        ),
    ]
