# Generated by Django 4.1.1 on 2023-01-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataControl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
