# Generated by Django 4.1.1 on 2023-01-17 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataControl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('code', models.TextField()),
                ('language', models.CharField(default='*name folder', max_length=50)),
                ('order', models.IntegerField(default=1)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dataControl.document')),
            ],
        ),
    ]
