# Generated by Django 4.1.1 on 2023-01-10 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataControl', '0003_folder_document_folder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Folder',
            new_name='Tag',
        ),
        migrations.RenameField(
            model_name='document',
            old_name='folder',
            new_name='tag',
        ),
    ]
