export const USER_UNIQUE_REQUEST = 'USER_UNIQUE_REQUEST'
export const USER_UNIQUE_SUCCES = 'USER_UNIQUE_SUCCES'
export const USER_UNIQUE_FAIL = 'USER_UNIQUE_FAIL'

export const POST_USER_REQUEST = 'POST_USER_REQUEST'
export const POST_USER_SUCCES = 'POST_USER_SUCCES'
export const POST_USER_FAIL = 'POST_USER_FAIL'