export const TAG_LIST_REQUEST = 'TAG_LIST_REQUEST'
export const TAG_LIST_SUCCES = 'TAG_LIST_SUCCES'
export const TAG_LIST_FAIL = 'TAG_LIST_FAIL'

export const TAG_POST_REQUEST = 'TAG_POST_REQUEST'
export const TAG_POST_SUCCES = 'TAG_POST_SUCCES'
export const TAG_POST_FAIL = 'TAG_POST_FAIL'

export const TAG_DELETE_REQUEST = 'TAG_DELETE_REQUEST'
export const TAG_DELETE_SUCCES = 'TAG_DELETE_SUCCES'
export const TAG_DELETE_FAIL = 'TAG_DELETE_FAIL'

export const TAG_UPDATE_REQUEST = 'TAG_UPDATE_REQUEST'
export const TAG_UPDATE_SUCCES = 'TAG_UPDATE_SUCCES'
export const TAG_UPDATE_FAIL = 'TAG_UPDATE_FAIL'

