export const DOCUMENT_LIST_REQUEST = 'DOCUMENT_LIST_REQUEST'
export const DOCUMENT_LIST_SUCCES = 'DOCUMENT_LIST_SUCCES'
export const DOCUMENT_LIST_FAIL = 'DOCUMENT_LIST_FAIL'

export const DOCUMENT_POST_REQUEST = 'DOCUMENT_POST_REQUEST'
export const DOCUMENT_POST_SUCCES = 'DOCUMENT_POST_SUCCES'
export const DOCUMENT_POST_FAIL = 'DOCUMENT_POST_FAIL'

export const DOCUMENT_DELETE_REQUEST = 'DOCUMENT_DELETE_REQUEST'
export const DOCUMENT_DELETE_SUCCES = 'DOCUMENT_DELETE_SUCCES'
export const DOCUMENT_DELETE_FAIL = 'DOCUMENT_DELETE_FAIL'

export const DOCUMENT_UPDATE_REQUEST = 'DOCUMENT_UPDATE_REQUEST'
export const DOCUMENT_UPDATE_SUCCES = 'DOCUMENT_UPDATE_SUCCES'
export const DOCUMENT_UPDATE_FAIL = 'DOCUMENT_UPDATE_FAIL'

export const IMAGE_LIST_REQUEST = 'IMAGE_LIST_REQUEST'
export const IMAGE_LIST_SUCCES = 'IMAGE_LIST_SUCCES'
export const IMAGE_LIST_FAIL = 'DOCUMENT_LIST_FAIL'

export const IMAGE_POST_REQUEST = 'IMAGE_POST_REQUEST'
export const IMAGE_POST_SUCCES = 'IMAGE_POST_SUCCES'
export const IMAGE_POST_FAIL = 'DOCUMENT_POST_FAIL'