export const DOCUMENT_LIST_REQUEST = 'DOCUMENT_LIST_REQUEST'
export const DOCUMENT_LIST_SUCCES = 'DOCUMENT_LIST_SUCCES'
export const DOCUMENT_LIST_FAIL = 'DOCUMENT_LIST_FAIL'

export const DOCUMENT_POST_REQUEST = 'DOCUMENT_POST_REQUEST'
export const DOCUMENT_POST_SUCCES = 'DOCUMENT_POST_SUCCES'
export const DOCUMENT_POST_FAIL = 'DOCUMENT_POST_FAIL'

export const IMAGE_LIST_REQUEST = 'IMAGE_LIST_REQUEST'
export const IMAGE_LIST_SUCCES = 'IMAGE_LIST_SUCCES'
export const IMAGE_LIST_FAIL = 'DOCUMENT_LIST_FAIL'