export const CODE_LIST_REQUEST = 'CODE_LIST_REQUEST'
export const CODE_LIST_SUCCES = 'CODE_LIST_SUCCES'
export const CODE_LIST_FAIL = 'CODE_LIST_FAIL'

export const CODE_POST_REQUEST = 'CODE_POST_REQUEST'
export const CODE_POST_SUCCES = 'CODE_POST_SUCCES'
export const CODE_POST_FAIL = 'CODE_POST_FAIL'

export const CODE_DELETE_REQUEST = 'CODE_DELETE_REQUEST'
export const CODE_DELETE_SUCCES = 'CODE_DELETE_SUCCES'
export const CODE_DELETE_FAIL = 'CODE_DELETE_FAIL'

export const CODE_UPDATE_REQUEST = 'CODE_UPDATE_REQUEST'
export const CODE_UPDATE_SUCCES = 'CODE_UPDATE_SUCCES'
export const CODE_UPDATE_FAIL = 'CODE_UPDATE_FAIL'